service: sadhanaSourceUsers

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  environment:
    NODE_ENV: dev

plugins:
  - serverless-plugin-typescript 
  - serverless-offline

functions:
  list:
    handler: app/handler.list
    events:
      - http:
          path: users
          method: get
  create:
    handler: app/handler.create
    events:
      - http:
          path: users
          method: post
  update:
    handler: app/handler.update
    events:
      - http:
          path: users
          method: put
  authenticate:
    handler: app/handler.authenticate
    events:
      - http:
          path: users/login
          method: post
  listPermissions:
    handler: app/handler.listPermissions
    events:
      - http:
          path: users/permissions
          method: get